### ISSUE TITLE
VisualStudioのソリューションファイルがImportされていない

### ISSUE THREAD

**Issue by gikoneko2ch** [JoyToMouse/jtm4Evenicle#4]
特に理由がなければ追加をお願いします。
他にも不足してるファイルがあるかもしれません。。。

**Comment by kruuRAiCE** [comment]
依存関係はなく、余計な情報入れたくなかったので JoyToAny.csproj のみとしました。
csproj ファイルを叩いてVisual Studioで開き、そのまま保存しようとすると勝手にソリューション保存しようとしてくれます。
もしデバッグ初期化失敗エラーがでる場合は、
メニュー＞デバッグ＞例外から Managed Debugging Assign の LoaderLock をオフにすれば解決します

不足ファイルについては、含まれてないファイルをソリューションエクスプローラから削除
プロジェクトのビルドオプションで条件付きコンパイルの WITHMANAGER を削除すれば
提供しているバイナリと同じものがビルドできます。

上記の処理しなくてもビルド通るように csproj ファイル更新しておきます

**Comment by kruuRAiCE** [comment]
JoyToAny.csproj 更新しました。
コードをcheckoutしたままビルド通るのを確認済みです
デバッグ時に

.USE_KEYS[0x01] = true; // LButton

でエラーでる場合は上の設定変更をすれば解決するのも確認済みです

**Comment by gikoneko2ch** [comment]
了解ですー。
一個のプロジェクトのみという方法なら不要かと思います。
イメージマップエディタ等を別プロジェクトにするつもりはありませんか？

**Comment by gikoneko2ch** [comment]
最新のソースをチェックアウト（プル？）し、警告・エラーが発生しないことを確認しました。
また、以下の手順を実施し、問題なくデバッグできることを確認しました。
「メニュー＞デバッグ＞例外から Managed Debugging Assign の LoaderLock をオフにすれば解決します」

ご対応ありがとうございました。

**Comment by kruuRAiCE** [comment]
イメージマップエディタはソースコードが恥ずかしい状態なので「まだ」非公開なだけです。
私にしか扱えない機能的にバギーな状態なので最低限のブラッシュアップ完了した時点でこのプロジェクトにファイル追加します。

当方では設定画面のシーン名のダブルクリックで起動するようになってます。 コードでは #ifdef で除外中

**Comment by gikoneko2ch** [comment]
一個のプロジェクト内に含むならソリューションファイルは不要ですねー。
ブラッシュアップしたらぜひ追加してくださいｗ
